-- -- This script was generated by the ERD tool in pgAdmin 4.
-- -- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
-- BEGIN;


-- CREATE TABLE IF NOT EXISTS public.kava_bar_details
-- (
--     id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
--     bar_name text COLLATE pg_catalog."default" NOT NULL,
--     about_bar text COLLATE pg_catalog."default" NOT NULL,
--     ratings numeric(3, 1),
--     CONSTRAINT kava_bar_details_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS public.kava_bar_location
-- (
--     id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
--     latitude double precision NOT NULL,
--     longitude double precision NOT NULL,
--     address character varying(255) COLLATE pg_catalog."default" NOT NULL,
--     CONSTRAINT kava_bar_location_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS public.user_reviews
-- (
--     id integer NOT NULL DEFAULT nextval('user_reviews_id_seq'::regclass),
--     kava_bar_detail_id integer NOT NULL,
--     user_id bigint NOT NULL,
--     review_text text COLLATE pg_catalog."default",
--     CONSTRAINT user_reviews_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS public.users
-- (
--     id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100 CACHE 1 ),
--     username character varying(50) COLLATE pg_catalog."default" NOT NULL,
--     email character varying(200) COLLATE pg_catalog."default" NOT NULL,
--     password character varying(300) COLLATE pg_catalog."default" NOT NULL,
--     CONSTRAINT users_pkey PRIMARY KEY (id),
--     CONSTRAINT unique_email UNIQUE (email)
-- );

-- ALTER TABLE IF EXISTS public.kava_bar_details
--     ADD CONSTRAINT fk_kava_bar_details_location FOREIGN KEY (id)
--     REFERENCES public.kava_bar_location (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE CASCADE
--     NOT VALID;
-- CREATE INDEX IF NOT EXISTS kava_bar_details_pkey
--     ON public.kava_bar_details(id);


-- ALTER TABLE IF EXISTS public.user_reviews
--     ADD CONSTRAINT user_reviews_kava_bar_detail_id_fkey FOREIGN KEY (kava_bar_detail_id)
--     REFERENCES public.kava_bar_details (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE NO ACTION;


-- ALTER TABLE IF EXISTS public.user_reviews
--     ADD CONSTRAINT user_reviews_user_id_fkey FOREIGN KEY (user_id)
--     REFERENCES public.users (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE NO ACTION;

-- END;